# Generated by Django 5.0.3 on 2024-04-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=250, verbose_name='bookName')),
                ('bookannotation', models.TextField(verbose_name='bookAnnotation')),
                ('pageamount', models.IntegerField(verbose_name='pageAmount')),
                ('bookamount', models.IntegerField(verbose_name='bookAmount')),
                ('registrationnumber', models.CharField(max_length=10, verbose_name='registrationNumber')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
