# Generated by Django 5.0.3 on 2024-04-23 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='genere',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='books.genres'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='language',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='books.languages'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='writer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='books.writers'),
            preserve_default=False,
        ),
    ]
