# Generated by Django 5.0.3 on 2024-04-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_books_genere_books_language_books_writer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='genere',
            new_name='genre',
        ),
        migrations.AddField(
            model_name='books',
            name='cover',
            field=models.ImageField(blank=True, upload_to='cover/'),
        ),
    ]
