# Generated by Django 5.0.4 on 2024-04-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rename_genere_books_genre_books_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='bookname',
            field=models.CharField(max_length=50, verbose_name='bookName'),
        ),
    ]
