# Generated by Django 5.0.4 on 2024-04-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_books_bookname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genres',
            name='genre',
            field=models.CharField(max_length=50, verbose_name='genre'),
        ),
        migrations.AlterField(
            model_name='languages',
            name='language',
            field=models.CharField(max_length=50, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='writers',
            name='writername',
            field=models.CharField(max_length=50, verbose_name='writername'),
        ),
    ]
