# Generated by Django 5.0.4 on 2024-05-07 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_borrowedbooks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowedbooks',
            old_name='registrationnumber',
            new_name='bookname',
        ),
    ]
