# Generated by Django 5.0.4 on 2024-05-14 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_reservedbooks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowedbooks',
            options={'verbose_name': 'Книга в процессе чтения', 'verbose_name_plural': 'Книги в процессе чтения'},
        ),
        migrations.AlterModelOptions(
            name='reservedbooks',
            options={'verbose_name': 'Зарезервированная книга', 'verbose_name_plural': 'Зарезервированные книги'},
        ),
        migrations.CreateModel(
            name='BooksHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Моя история',
                'verbose_name_plural': 'Моя история',
            },
        ),
    ]
