# Generated by Django 5.0.4 on 2024-05-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_borrowedbooks_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='deletion_requested',
            field=models.BooleanField(default=False),
        ),
    ]
