# Generated by Django 5.0.4 on 2024-05-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_books_deletion_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
